### ISSUE TITLE
IProblem Interface Enums

### ISSUE THREAD

**Issue by MohamedBeydoun** [Compete-McGill/wisp-problems-microservice#20]
The IProblem interface used to set the fields "platformMetadata.difficulty" and "source" as type "Difficulty" and "PlatformName" respectively. This offered no validation for the values in the controllers and restricted values to 0, 1, and 2 when setting the fields manually. Currently, if the request body's value is different from the ones in the enums, the interface does nothing and it's up to mongo to throw the errors -> status 500. The types of these fields has since been changed in the interface to "string" in order to accomodate setting the values to strings instead of the ints 0, 1, and 2. From there, we now need to add custom validators to check if the request body values are indeed expected values.

For custim validators,  see the `validateProblemSetIds` function in src/validators/problem

**Comment by idodin** [comment]
Resolving this with the same PR as #17 so I'm assigning myself

**Comment by MohamedBeydoun** [comment]
@idodin the issue states that "The types of these fields has since been changed in the interface to "string" in order to accomodate setting the values to strings instead of the ints 0, 1, and 2." but that's not true since the PR for that hasn't been merged. Could you change them to strings in ur PR?

**Comment by idodin** [comment]
@MohamedBeydoun Just saw this, will update PR
