### ISSUE TITLE
Problem model's platformProblemId should be standardized

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp-problems-microservice#35]
platformProblemId (i.e. "1A" for Codeforces) should either always be uppercase or lowercase. Currently, either can be sent through the POST or PUT routes, and these result in different `problemId` hashes ("1A" vs "1a" hashes to different results).

Also need to check with `wisp-users-microservice` to see how we're doing it there, and we should standardize it there as well.

**Comment by MohamedBeydoun** [comment]
We already discussed this and decided to go with uppercase (see wisp-users)

**Comment by MohamedBeydoun** [comment]
Seems to also be implemented in the problems microservice:
![image](https://user-images.githubusercontent.com/41027939/83820276-415cda00-a69a-11ea-9138-7d0ff10c3929.png)

**Comment by ValerianClerc** [comment]
Yeah my bad, misread our code. I know we discussed this, I just didn't see where we implemented this in the problems microservice (thought we forgot about it)
