### ISSUE TITLE
Orphan Problem Do not get Deleted when no longer associated to a Problem Set

### ISSUE THREAD

**Issue by AsFal** [Compete-McGill/wisp-problems-microservice#50]
**Ignore** if this is meant as a feature.

## Steps to reproduce
1. Login with an Admin account
2. Create a problem set
3. Create a problem and add it to that problem set
4. Delete the problem set
5. Go to the /problems page. The orphan problem will appear in the table.

**Comment by ValerianClerc** [comment]
Sorry that this isn't documented clearly anywhere, but this is actually the intended behaviour. The idea is that problems can belong to many problemSets, or to no problemSets. It's not a total participation relationship.
