### ISSUE TITLE
CI/CD Improvements

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp-problems-microservice#8]
@idodin could we use the github short SHA as a tag instead of the full SHA?

Also I don’t think we need to push twice: right now we’re pushing once for the GitHub SHA tag and once for the “latest” tag. I believe that the images can have multiple tags, and can be pushed/referred to by either tag. And these tags persist when we push the image. @MohamedBeydoun can confirm this though

**Comment by MohamedBeydoun** [comment]
yeah docker images can be tagged multiple times
